version: 2

general:
  branches:
    ignore:
      - gh-pages

jobs:
  build:
    docker:
      - image: circleci/node:8.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: build
          command: npm run prod

      - deploy:
          name: deployment on GitHub pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              GITURL=`git config remote.origin.url`
              cd public
              rm -rf .git/
              git config --global user.email "$GH_EMAIL"
              git config --global user.name "$GH_NAME"
              git init
              git remote add origin $GITURL
              echo "$DOMAIN" > CNAME
              git add .
              git commit -am "Automated Rebuild"
              git push origin master:gh-pages --force
            fi
